kvm1:
    address: ENC[AES256_GCM,data:c23tyAFY/UzwOIP+P9zMmZJcNirkxHqtIfc=,iv:3o5PcHGJNBlE0ChTAFVFwmf8LhoGPJsI76x4xH8rLjw=,tag:/oixVl/U8M4K/k3x/T7+vw==,type:str]
    user: ENC[AES256_GCM,data:/LtapQ==,iv:jYPs+dkY/l2olGuUxFmpQmQ5Z/WcJ9LA4JWW9vSjJ3c=,tag:ubP5YxxISuNg+Cr4LYIBfg==,type:str]
kvm2:
    address: ENC[AES256_GCM,data:ScnZh/jzdbR2nm6inlqU1g+U8f8KyljekgU=,iv:Id46VRPLx7sHtKYAQPJk4B7eTlG7CEc5jCaiVytAekw=,tag:/b7+3tTC3bPIIglurj7FPA==,type:str]
    user: ENC[AES256_GCM,data:zym3Xg==,iv:K87j3U7brJcNUrCmASQ1mOtJOCu9fHOfHiGR4mS3rrw=,tag:5+vtsf+pWP7qU+r9/n7/Ww==,type:str]
kvm3:
    address: ENC[AES256_GCM,data:ggBo3u/gh9cP1AZGybF00QZUxLKYCrCPXLU=,iv:/FD1xJ2lqpGYtShHLS/Y70Kuz4QRFJyprAYpoZ+XgPc=,tag:U2glObfYwA+9PR3d+HDa7Q==,type:str]
    user: ENC[AES256_GCM,data:MvPc0aRn,iv:9Eyhe4YoIkcWT1airl1gwlQAR7vz2EIY6E3jBAapQwM=,tag:0LNX3rR1Jv4bjhO6DEPbRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ety65vhtrhlevgmm899eyvdmv4avfm0replxg5tz6a2jyq84n4us7ryfc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGRZSGVTYU9Pc1h6WS9s
            YXhHWFRCcHpJeDhsYzJmZ28rSllsc0NoUFVBClVtSUFMSklYR1pPSEtjOVdvQk95
            UkxweDk3RzRnRXp6ZE5uSHpvVzM5TjgKLS0tIE5BcFFrY2Y1QWlVclRFWWxuSmdL
            MUF5OFNsd2I4dGlBRGdyVDJ3dmRWa2MKqC/3/cFD++iQIDGzQJ8iP3aSTvDysb/C
            bLD1sz3gOwQe05Gfqp9p34sCtIPQV3zB1whktRfr6d/oax0Jkm1Z3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-25T10:01:08Z"
    mac: ENC[AES256_GCM,data:QufTAstgII7QqKDmvOJk4jx4+9RkoJ7CZOhIM6ySoN/TFk3fhgtGzEDId0ll8tvOLgEHOXMLl5ou2zg5aaTMw3WkW9dpzEgs2u09M1NsqAnZJ65Za9lZa9BN+TOfw1JP1jjFKrOxW8xIVRNmrrhrTXKR2q3OSxALG4N2kiEUl+k=,iv:DtRH5Np18cgKQqFE4v66f/YCHQ76pY3NjqUfcOl6oYo=,tag:5uZpNGEoMM3+DoALZjbafQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
