---
- name: DNS | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - dns-server
    - powerdns
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# PowerDNS
- name: Powerdns
  ansible.builtin.import_tasks: powerdns.yml
  tags:
    - dns-server
    - powerdns
  when: ansible_facts.os_family == 'Debian'

# Flush Handlers
- name: DNS | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - dns-server
