---
- name: DNS | Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - dns-server
    - powerdns

- name: DNS | Powerdns
  ansible.builtin.import_tasks: powerdns.yml
  tags:
    - dns-server
    - powerdns

- name: DNS | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - dns-server
    - powerdns
