---
- name: PXE | Start
  ansible.builtin.import_tasks: start.yml
  tags:
    - pxe_boot
    - start
  when: ansible_facts['distribution'] == 'Fedora'

- name: PXE | Stop
  ansible.builtin.import_tasks: stop.yml
  tags:
    - pxe_boot
    - stop
  when: ansible_facts['distribution'] == 'Fedora'
