repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.3.0
    hooks:
      - id: ansible-lint
        args: [
          "--project-dir",
          "ansible"
        ]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/bridgecrewio/checkov
    rev: '2.0.1065'
    hooks:
      - id: checkov
        args: [
          "--quiet",
          "--compact",
          "--download-external-modules=True"
        ]
