---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        args: [
          "--config-file=.ansible-lint.yml",
          "--project-dir=ansible"
        ]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs

  - repo: https://github.com/bridgecrewio/checkov
    rev: '3.2.489'
    hooks:
      - id: checkov
        args: [
          "--quiet",
          "--compact",
          "--download-external-modules=True"
        ]
