---

extends: default

rules:
  line-length:
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  truthy:
    ignore: |
      .github/workflows

# yaml-files:
#  - '*.yaml'
#  - '*.yml'
#  - '.yamllint'

# rules:
#  braces: enable
#  brackets: enable
#  colons: enable
#  commas: enable
#  comments:
#    level: warning
#  comments-indentation:
#    level: warning
#  document-end: disable
#  document-start:
#    level: warning
#  empty-lines: enable
#  empty-values: disable
#  hyphens: enable
#  indentation: enable
#  key-duplicates: enable
#  key-ordering: disable
#  line-length: enable
#  new-line-at-end-of-file: enable
#  new-lines: enable
#  octal-values: disable
#  quoted-strings: disable
#  trailing-spaces: enable
#  truthy:
#    level: warning
