---
- name: Database | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - database
    - mariadb
    - mariadb-secure
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# MariaDB Configuration
- name: Mariadb
  ansible.builtin.import_tasks: mariadb.yml
  tags:
    - database
    - mariadb
  when: ansible_facts.os_family == 'Debian'

# MariaDB Secure Installation
- name: Mariadb-secure
  ansible.builtin.import_tasks: mariadb-secure.yml
  tags:
    - database
    - mariadb-secure
  when: ansible_facts.os_family == 'Debian'

# Flush Handlers
- name: Database | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - database
