---
- name: database | set variables
  include_vars: '{{ item }}'
  tags:
    - database
    - mariadb
    - mariadb-secure
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# MariaDB Configuration
- name: mariadb
  ansible.builtin.import_tasks: mariadb.yml
  tags:
    - database
    - mariadb
  when: ansible_facts.os_family == 'Debian'

# MariaDB Secure Installation
- name: mariadb-secure
  ansible.builtin.import_tasks: mariadb-secure.yml
  tags:
    - database
    - mariadb-secure
  when: ansible_facts.os_family == 'Debian'

# Flush Handlers
- name: database | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - database
