---
- name: calico | install calico
  ansible.builtin.shell:
    chdir: /opt/homelab/kubernetes/core/calico-system
    cmd: |
      helm dependencies update &&
      kubectl create namespace calico-system &&
      helm install -n calico-system calico-system . -f values.yaml
    creates: /opt/cni/bin/install
  run_once: true
  tags:
    - kubernetes
    - kubernetes-controller
    - calico
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']
    - pacemaker_cluster_ip in ansible_facts['all_ipv4_addresses']
