---
- name: Encryption | configure /etc/kubernetes/secrets/encryption-config.yaml
  ansible.builtin.template:
    src: etc/kubernetes/secrets/encryption-config.yaml.j2
    dest: /etc/kubernetes/secrets/encryption-config.yaml
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

- name: Encryption | configure /etc/kubernetes/manifests/kube-apiserver.yaml
  ansible.builtin.template:
    src: etc/kubernetes/manifests/kube-apiserver.yaml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - pause for apiserver
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

- name: Encryption | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
