---
- name: flux | download archived flux binary
  ansible.builtin.get_url:
    url: https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz
    dest: /etc/kubernetes/flux_{{ flux_version }}_linux_amd64.tar.gz
    checksum: '{{ flux_binary_checksum }}'
    timeout: 30
    owner: root
    group: root
    mode: '644'
  tags:
    - kubernetes
    - kubernetes-controller
    - flux
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['architecture'] == 'x86_64'
    - inventory_hostname in groups['k8s_controllers']

- name: flux | extract flux binary
  ansible.builtin.unarchive:
    src: /etc/kubernetes/flux_{{ flux_version }}_linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    owner: root
    group: root
    mode: '755'
  tags:
    - kubernetes
    - kubernetes-controller
    - flux
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['architecture'] == 'x86_64'
    - inventory_hostname in groups['k8s_controllers']
