---
- name: helm | download archived helm binary
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: /etc/kubernetes/helm-{{ helm_version }}-linux-amd64.tar.gz
    checksum: '{{ helm_binary_checksum }}'
    timeout: 30
    owner: root
    group: root
    mode: '644'
  tags:
    - kubernetes
    - kubernetes-controller
    - helm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['architecture'] == 'x86_64'
    - inventory_hostname in groups['k8s_controllers']

- name: helm | extract helm binary
  ansible.builtin.unarchive:
    src: /etc/kubernetes/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    exclude:
      - linux-amd64/LICENSE
      - linux-amd64/README.md
    extra_opts:
      - --strip-components=1
    owner: root
    group: root
    mode: '755'
  tags:
    - kubernetes
    - kubernetes-controller
    - helm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['architecture'] == 'x86_64'
    - inventory_hostname in groups['k8s_controllers']
