---
- name: Kubernetes Controller | check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - kubernetes
    - kubernetes-controller
    - network
    - pacemaker
    - pki
    - encryption
    - helm
    - kubeadm
    - argocd
    - kubeseal
    - git-repo
    - calico

- name: Kubernetes Controller | network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - network
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | pacemaker
  ansible.builtin.import_tasks: pacemaker.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pacemaker
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - directories
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | pki
  ansible.builtin.import_tasks: pki.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pki
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | kubeadm
  ansible.builtin.import_tasks: kubeadm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeadm
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | encryption
  ansible.builtin.import_tasks: encryption.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | helm
  ansible.builtin.import_tasks: helm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - helm
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | argocd
  ansible.builtin.import_tasks: argocd.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - argocd
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | kubeseal
  ansible.builtin.import_tasks: kubeseal.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeseal
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | gitrepo
  ansible.builtin.import_tasks: gitrepo.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - git-repo
  when:
    - inventory_hostname in groups['k8s_controllers']

- name: Kubernetes Controller | calico
  ansible.builtin.import_tasks: calico.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - calico
  when:
    - inventory_hostname in groups['k8s_controllers']
