---
- name: kubernetes-controller | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - kubernetes
    - kubernetes-controller
    - network
    - pacemaker
    - pki
    - encryption
    - helm
    - kubeadm
    - calico
    - flux
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# Network
- name: network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - network
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Pacemaker
- name: pacemaker
  ansible.builtin.import_tasks: pacemaker.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pacemaker
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Directories
- name: directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - directories
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# PKI
- name: kubernetes-pki
  ansible.builtin.import_tasks: pki.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pki
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Encryption
- name: encryption
  ansible.builtin.import_tasks: encryption.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Helm
- name: helm
  ansible.builtin.import_tasks: helm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - helm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Kubeadm
- name: kubeadm
  ansible.builtin.import_tasks: kubeadm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeadm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Calico
- name: calico
  ansible.builtin.import_tasks: calico.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - calico
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Flux
- name: flux
  ansible.builtin.import_tasks: flux.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - flux
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']
