---
- name: Kubernetes Controller | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - kubernetes
    - kubernetes-controller
    - network
    - pacemaker
    - pki
    - encryption
    - helm
    - kubeadm
    - argocd
    - kubeseal
    - git-repo
    - calico
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

# Network
- name: Network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - network
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Pacemaker
- name: Pacemaker
  ansible.builtin.import_tasks: pacemaker.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pacemaker
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Directories
- name: Directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - directories
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# PKI
- name: PKI
  ansible.builtin.import_tasks: pki.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - pki
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Kubeadm
- name: Kubeadm
  ansible.builtin.import_tasks: kubeadm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeadm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Encryption
- name: Encryption
  ansible.builtin.import_tasks: encryption.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Helm
- name: Helm
  ansible.builtin.import_tasks: helm.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - helm
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# ArgoCD CLI
- name: ArgoCD
  ansible.builtin.import_tasks: argocd.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - argocd
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# KubeSeal
- name: KubeSeal
  ansible.builtin.import_tasks: kubeseal.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeseal
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Gitrepo
- name: Gitrepo
  ansible.builtin.import_tasks: gitrepo.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - git-repo
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']

# Calico
- name: Calico
  ansible.builtin.import_tasks: calico.yml
  tags:
    - kubernetes
    - kubernetes-controller
    - calico
  when:
    - ansible_facts['os_family'] == 'Debian'
    - inventory_hostname in groups['k8s_controllers']
