---
- name: Pacemaker | pause to allow floating ip address to come online
  ansible.builtin.pause:
    seconds: 30
  listen: pause for pacemaker
  tags:
    - kubernetes
    - kubernetes-controller
    - pacemaker

- name: Encryption | pause to allow kube-apiserver to redeploy
  ansible.builtin.pause:
    seconds: 60
  listen: pause for apiserver
  tags:
    - kubernetes
    - kubernetes-controller
    - encryption

- name: Calico | pause to allow calico to fully deploy
  ansible.builtin.pause:
    seconds: 150
  listen: pause for calico
  tags:
    - kubernetes
    - kubernetes-controller
    - calico

- name: KubeSeal | apply sealed-secrets label to custom-sealed-secrets-key secret
  ansible.builtin.command:
    argv:
      - kubectl
      - label
      - secret
      - 'custom-sealed-secrets-key'
      - sealedsecrets.bitnami.com/sealed-secrets-key=active
      - -n
      - 'kube-system'
  listen: kubeseal label secret
  tags:
    - kubernetes
    - kubernetes-controller
    - kubeseal
