---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-vol
  namespace: traefik-infra
spec:
  storageClassName: cstor-stripe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
