---
- name: auto-updates | install unattended-upgrades package
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'Debian'

- name: auto-updates | configure /etc/apt/apt.conf.d/20auto-upgrades
  ansible.builtin.copy:
    src: etc/apt/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '644'
  notify: restart unattended-upgrades
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'Debian'

- name: auto-updates | configure /etc/apt/apt.conf.d/50unattended-upgrades
  ansible.builtin.template:
    src: templates/etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '644'
  notify: restart unattended-upgrades
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'Debian'

- name: auto-updates | start and enable unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'Debian'
