---
- name: Auto-updates | install yum-cron package
  ansible.builtin.yum:
    name: yum-cron
    state: present
    update_cache: true
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'RedHat'

- name: Auto-updates | configure /etc/yum/yum-cron.conf
  ansible.builtin.template:
    src: etc/yum/yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
    owner: root
    group: root
    mode: '644'
  notify: restart yum-cron
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'RedHat'

- name: Auto-updates | start and enable yum-cron service
  ansible.builtin.service:
    name: yum-cron
    state: started
    enabled: true
  tags:
    - common
    - auto-updates
  when: ansible_facts['os_family'] == 'RedHat'
