---
- name: Firewall | install firewalld package
  ansible.builtin.yum:
    name: firewalld
    state: present
    update_cache: true
  tags:
    - common
    - firewall
  when: ansible_facts['os_family'] == 'RedHat'

- name: Firewall | set default zone
  ansible.posix.firewalld:
    zone: block
    interface: eth0
    permanent: true
    state: enabled
  tags:
    - common
    - firewall
  when: ansible_facts['os_family'] == 'RedHat'

- name: Firewall | allow ssh inbound
  ansible.posix.firewalld:
    service: ssh
    zone: block
    permanent: true
    state: enabled
  tags:
    - common
    - firewall
  when: ansible_facts['os_family'] == 'RedHat'

- name: Firewall | allow dhcp inbound
  ansible.posix.firewalld:
    service: dhcpv6-client
    zone: block
    permanent: true
    state: enabled
  tags:
    - common
    - firewall
  when: ansible_facts['os_family'] == 'RedHat'
