---
- name: Common | Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - common
    - network
    - firewall
    - ntp
    - packages
    - auto-updates
    - users

- name: Common | populate service facts
  ansible.builtin.service_facts:
  tags:
    - common
    - network
    - firewall
    - ntp
    - packages
    - auto-updates
    - users

- name: Common | Network
  ansible.builtin.import_tasks: network.yml
  tags:
    - common
    - network

- name: Common | Firewall
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - common
    - firewall

- name: Common | NTP
  ansible.builtin.import_tasks: ntp.yml
  tags:
    - common
    - ntp

- name: Common | Packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - common
    - packages

- name: Common | Auto-updates
  ansible.builtin.import_tasks: auto-update.yml
  tags:
    - common
    - auto-updates

- name: Common | Users
  ansible.builtin.import_tasks: users.yml
  tags:
    - common
    - users

- name: Common | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - common
    - network
    - firewall
    - ntp
    - packages
    - auto-updates
    - users
