---
- name: main | set variables
  include_vars: '{{ item }}'
  tags:
    - common
    - network
    - firewall
    - ntp
    - packages
    - auto-updates
    - users
    - sudo
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# Network
- import_tasks: network.yml
  tags:
    - common
    - network

# Firewall
- name: firewall
  ansible.builtin.include_tasks:
    file: firewall-{{ ansible_facts.os_family }}.yml
    apply:
      tags:
        - common
        - firewall

# NTP
- import_tasks: ntp.yml
  tags:
    - common
    - ntp

# Packages
- import_tasks: packages.yml
  tags:
    - common
    - packages

# Auto Updates
- name: auto-updates
  ansible.builtin.include_tasks:
    file: auto-update-{{ ansible_facts.os_family }}.yml
    apply:
      tags:
        - common
        - auto-updates

# Users
- import_tasks: users.yml
  tags:
    - common
    - users

# Sudo
- import_tasks: sudo.yml
  tags:
    - common
    - sudo
