---
- name: Network | update hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  tags:
    - common
    - network
  when: ansible_facts.hostname != inventory_hostname

- name: Network | configure /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: '{{ main_root_group }}'
    mode: '644'
  tags:
    - common
    - network

- name: Network | configure /etc/hosts
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: '{{ main_root_group }}'
    mode: '644'
  tags:
    - common
    - network
