---
- name: network | update hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  when: ansible_facts.hostname != inventory_hostname

- name: network | configure /etc/resolv.conf
  ansible.builtin.template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '644'

- name: network | configure /etc/hosts
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '644'
