---
- name: NTP | install ntp package
  ansible.builtin.apt:
    name: ntp
    state: present
    update_cache: true
  tags:
    - common
    - firewall

- name: NTP | update timezone
  community.general.timezone:
    name: '{{ timezone }}'
  tags:
    - common
    - ntp

- name: NTP | configure /etc/ntp.conf
  ansible.builtin.copy:
    src: etc/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '644'
  notify:
    - restart ntp
  tags:
    - common
    - ntp

- name: NTP | start and enable ntp service
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
  tags:
    - common
    - ntp
