---
- name: NTP | update timezone
  community.general.timezone:
    name: '{{ timezone }}'
  tags:
    - common
    - ntp

- name: NTP | install ntp package
  ansible.builtin.package:
    name: ntp
    state: present
  tags:
    - common
    - ntp
  when: ansible_facts['os_family'] != 'FreeBSD'

- name: NTP | configure /etc/ntp.conf
  ansible.builtin.copy:
    src: etc/ntp-{{ ansible_facts['os_family'] }}.conf
    dest: /etc/ntp.conf
    owner: root
    group: '{{ main_root_group }}'
    mode: '644'
  notify:
    - restart ntp
  tags:
    - common
    - ntp

- name: NTP | start and enable {{ ntp_service_name }} service
  ansible.builtin.service:
    name: '{{ ntp_service_name }}'
    state: started
    enabled: true
  tags:
    - common
    - ntp
