---
- name: Users | install sudo package
  ansible.builtin.package:
    name: sudo
    state: present
  tags:
    - common
    - users

- name: Users | create admin users
  ansible.builtin.user:
    name: '{{ item }}'
    shell: /bin/bash
  loop: '{{ admin_users }}'
  tags:
    - common
    - users

- name: Users | configure e/tc/sudoers.d/20_admins_sudo
  ansible.builtin.template:
    src: etc/sudoers.d/20_admins_sudo.j2
    dest: /etc/sudoers.d/20_admins_sudo
    owner: root
    group: root
    mode: '644'
  tags:
    - common
    - users
