---
- name: powerdns | import database schema
  community.mysql.mysql_db:
    state: import
    name: '{{ powerdns_mysql_database_name }}'
    encoding: latin1
    target: '{{ powerdns_mysql_schema_path }}'
  listen: import database schema
  tags:
    - dns-server
    - powerdns
  when:
    - ansible_facts.os_family == 'Debian'
    - ansible_facts.hostname == mariadb_galera_bootstrap_host

- name: powerdns | restart powerdns
  ansible.builtin.service:
    name: '{{ powerdns_service_name }}'
    state: restarted
  listen: restart powerdns
  tags:
    - dns-server
    - powerdns
  when: ansible_facts.os_family == 'Debian'

- name: powerdns | restart powerdns-recursor
  ansible.builtin.service:
    name: '{{ powerdns_recursor_service_name }}'
    state: restarted
  listen: restart powerdns-recursor
  tags:
    - dns-server
    - powerdns
  when: ansible_facts.os_family == 'Debian'

- name: powerdns | import zone sql
  ansible.builtin.shell:
    cmd: mysql {{ powerdns_mysql_database_name }} < /etc/powerdns/zones.sql
  run_once: true
  listen: import zone sql
  tags:
    - dns-server
    - powerdns
  when:
    - ansible_facts['os_family'] == 'Debian'
