---
- name: Powerdns | import database schema
  community.mysql.mysql_db:
    state: import
    name: powerdns
    encoding: latin1
    target: /usr/share/pdns-backend-mysql/schema/schema.mysql.sql
  listen: import database schema
  tags:
    - dns-server
    - powerdns

- name: Powerdns | restart powerdns
  ansible.builtin.service:
    name: pdns
    state: restarted
  listen: restart powerdns
  tags:
    - dns-server
    - powerdns

- name: Powerdns | restart powerdns-recursor
  ansible.builtin.service:
    name: pdns-recursor
    state: restarted
  listen: restart powerdns-recursor
  tags:
    - dns-server
    - powerdns

- name: Powerdns | import zone sql
  ansible.builtin.shell:
    cmd: mysql powerdns < /etc/powerdns/zones.sql
  run_once: true
  listen: import zone sql
  tags:
    - dns-server
    - powerdns
