---
- name: KVM | install kvm and qemu packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ kvm_packages_list }}'
  tags:
    - kvm-hypervisor
    - kvm
  when: ansible_facts['os_family'] == 'Debian'

- name: KVM | install libvirt packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ libvirt_packages_list }}'
  tags:
    - kvm-hypervisor
    - kvm
  when: ansible_facts['os_family'] == 'Debian'

- name: KVM | start and enable {{ libvirt_service_name }} service
  ansible.builtin.service:
    name: '{{ libvirt_service_name }}'
    enabled: true
    state: started
  tags:
    - kvm-hypervisor
    - kvm
  when: ansible_facts['os_family'] == 'Debian'

- name: KVM | configure /etc/apparmor.d/libvirt/TEMPLATE.qemu
  ansible.builtin.copy:
    src: files/etc/apparmor.d/libvirt/TEMPLATE.qemu
    dest: /etc/apparmor.d/libvirt/TEMPLATE.qemu
    owner: root
    group: root
    mode: '644'
  tags:
    - kvm-hypervisor
    - kvm
  when: ansible_facts['os_family'] == 'Debian'
