---
- name: KVM | install kvm and qemu packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ kvm_packages_list }}'
  tags:
    - kvm-hypervisor
    - kvm

- name: KVM | install libvirt packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ libvirt_packages_list }}'
  tags:
    - kvm-hypervisor
    - kvm

- name: KVM | start and enable libvirtd service
  ansible.builtin.service:
    name: libvirtd
    enabled: true
    state: started
  tags:
    - kvm-hypervisor
    - kvm

- name: KVM | configure /etc/apparmor.d/libvirt/TEMPLATE.qemu
  ansible.builtin.copy:
    src: etc/apparmor.d/libvirt/TEMPLATE.qemu
    dest: /etc/apparmor.d/libvirt/TEMPLATE.qemu
    owner: root
    group: root
    mode: '644'
  tags:
    - kvm-hypervisor
    - kvm

- name: Users | update admin user groups
  ansible.builtin.user:
    name: '{{ item }}'
    append: true
    groups:
      - libvirt
  loop: '{{ admin_users }}'
  tags:
    - common
    - users
