---
- name: KVM Hypervisor | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - kvm-hypervisor
    - network
    - kvm
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

# Network
- name: Network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kvm-hypervisor
    - network
  when: ansible_facts['os_family'] == 'Debian'

# KVM
- name: KVM
  ansible.builtin.import_tasks: kvm.yml
  tags:
    - kvm-hypervisor
    - kvm
  when: ansible_facts['os_family'] == 'Debian'

# Flush Handlers
- name: KVM Hypervisor | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - kvm-hypervisor
