---
- name: KVM Hypervisor | Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - kvm-hypervisor
    - network
    - kvm

- name: KVM Hypervisor | Network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kvm-hypervisor
    - network

- name: KVM Hypervisor | KVM
  ansible.builtin.import_tasks: kvm.yml
  tags:
    - kvm-hypervisor
    - kvm

- name: KVM Hypervisor | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - kvm-hypervisor
    - network
    - kvm
