---
- name: network | install networking packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ network_packages_list }}'

- name: network | configure /etc/network/interfaces
  ansible.builtin.copy:
    src: files/etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '644'

- name: network | configure /etc/interfaces.d/br0
  ansible.builtin.copy:
    src: files/etc/network/interfaces.d/br0
    dest: /etc/network/interfaces.d/br0
    owner: root
    group: root
    mode: '644'
