---
- name: NTP | restart ntp
  ansible.builtin.service:
    name: ntp
    state: restarted
  listen: restart ntp
  tags:
    - common
    - ntp

- name: Auto-updates | restart unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
  listen: restart unattended-upgrades
  tags:
    - common
    - auto-updates
