---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.11.0
  interval: 10m
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.1.1.70-10.1.1.110
