---
debian_version: buster

main_packages_list:
  - htop
  - lsof
  - net-tools
  - screen
  - strace
  - telnet
  - vim
  - gpg
  - rsync
  - arping
  - dnsutils
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - tree
  - bash-completion
