---
domain: lab.alexgardner.id.au

nameservers:
  - '10.1.1.31'
  - '10.1.1.32'
  - '10.1.1.33'
  - '10.1.1.1'
network_subnets:
  - '10.1.1.0/24'
  - '10.1.2.0/24'
  - '10.1.3.0/24'

firewall_servers_subnet: 10.1.1.0/24
firewall_wireless_subnet: 10.1.2.0/24
firewall_clients_subnet: 10.1.3.0/24

timezone: Australia/Sydney
debian_version: buster

ansible_python_interpreter: /usr/bin/python3.7
