---
kubernetes_clients_hosts_list:
  - '10.1.3.100'
kubernetes_cluster_name: kubernetes
kubernetes_cluster_fqdn: k8s-controller.{{ domain }}
kubernetes_pod_network_cidr: 10.10.0.0/16
kubernetes_calico_network_cidr: 10.10.0.0/16

pacemaker_hosts_list: "{{ groups['k8s_controllers'] | map('extract', hostvars, 'ansible_host') | list }}"
pacemaker_hosts: "{{ groups['k8s_controllers'] }}"
pacemaker_primary_host: "{{ groups['k8s_controllers'][0] }}"
pacemaker_cluster_name: k8s-controller
pacemaker_cluster_ip: '10.1.1.40'

# Retrieved from https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz.sha256sum
helm_binary_checksum: sha256:c12d2cd638f2d066fec123d0bd7f010f32c643afdf288d39a4610b1f9cb32af3
helm_version: 'v3.10.1'

# Retrieved from https://github.com/argoproj/argo-cd/releases/download/v2.5.2/argocd-2.5.2-checksums.txt
argocd_binary_checksum: sha256:249a7409e8d602347668420ac4cb2c828565fe72d1b9bffb06bbf7c816ec38c6
argocd_version: 'v2.5.2'

# Retrieved from https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.2/sealed-secrets_0.19.2_checksums.txt
kubeseal_binary_checksum: sha256:f259f7d4754a882031f1ccfc6c004fa4646734e48f0e68c1adce72309ae16f03
kubeseal_version: '0.19.2'

git_repo_url: https://github.com/eyulf/homelab.git
git_branch: main
