---
kubernetes_clients_hosts_list:
  - '10.1.3.100'
kubernetes_cluster_name: kubernetes
kubernetes_cluster_fqdn: k8s-controller.{{ domain }}
kubernetes_pod_network_cidr: 10.10.0.0/16
kubernetes_calico_network_cidr: 10.10.0.0/16

pacemaker_hosts_list: "{{ groups['k8s_controllers'] | map('extract', hostvars, 'ansible_host') | list }}"
pacemaker_hosts: "{{ groups['k8s_controllers'] }}"
pacemaker_primary_host: "{{ groups['k8s_controllers'][0] }}"
pacemaker_cluster_name: k8s-controller
pacemaker_cluster_ip: '10.1.1.40'

# Retrieved from https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz.sha256sum
helm_binary_checksum: sha256:1484ffb0c7a608d8069470f48b88d729e88c41a1b6602f145231e8ea7b43b50a
helm_version: 'v3.9.0'

# Retrieved from https://github.com/argoproj/argo-cd/releases/download/v2.4.8/argocd-linux-amd64.sha256
argocd_binary_checksum: sha256:61417e13fa5ddaee66b8b3b10360dc57c8aaf5408f6f2faa479e6d679dbfc016
argocd_version: 'v2.4.8'

# Retrieved from https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/sealed-secrets_0.18.1_checksums.txt
kubeseal_binary_checksum: sha256:78875afdbfa958d06b4fe6e7ea63bdea8c7e944fda6425769e2a0394ac33899e
kubeseal_version: '0.18.1'

git_repo_url: https://github.com/eyulf/homelab.git
git_branch: main
