---
- name: database | restart mariadb
  ansible.builtin.service:
    name: '{{ mariadb_service_name }}'
    state: restarted
  listen: restart mariadb
  when: ( ansible_facts.hostname != mariadb_galera_bootstrap_host)
