---
# Pre-generated key created using `corosync-keygen`
- name: Corosync | configure /etc/corosync/authkey
  ansible.builtin.copy: # noqa template-instead-of-copy
    content: "{{ lookup('community.sops.sops', 'etc/corosync/authkey', rstrip=false) }}"
    dest: /etc/corosync/authkey
    owner: root
    group: root
    mode: '0400'
  tags:
    - pacemaker
    - corosync
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Corosync | configure /etc/corosync/corosync.conf
  ansible.builtin.template:
    src: etc/corosync/corosync.conf.j2
    dest: /etc/corosync/corosync.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart corosync
  tags:
    - pacemaker
    - corosync
  when:
    - ansible_facts['os_family'] == 'Debian'

# Flush Handlers
- name: Corosync | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - pacemaker
    - corosync
