---
- name: pacemaker | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - pacemaker
    - network
    - packages
    - services
    - corosync
    - settings
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# Network
- name: network
  ansible.builtin.import_tasks: network.yml
  tags:
    - pacemaker
    - network
  when: ansible_facts.os_family == 'Debian'

# Packages
- name: packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - pacemaker
    - packages
  when:
    - ansible_os_family == 'Debian'

# Services
- name: services
  ansible.builtin.import_tasks: services.yml
  tags:
    - pacemaker
    - services
  when:
    - ansible_os_family == 'Debian'

# Corosync
- name: corosync
  ansible.builtin.import_tasks: corosync.yml
  tags:
    - pacemaker
    - corosync
  when:
    - ansible_os_family == 'Debian'

# Settings
- name: settings
  ansible.builtin.import_tasks: settings.yml
  tags:
    - pacemaker
    - settings
  when:
    - ansible_os_family == 'Debian'
