---
- name: Pacemaker | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - pacemaker
    - network
    - packages
    - services
    - corosync
    - settings
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

# Network
- name: Network
  ansible.builtin.import_tasks: network.yml
  tags:
    - pacemaker
    - network
  when: ansible_facts['os_family'] == 'Debian'

# Packages
- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - pacemaker
    - packages
  when:
    - ansible_facts['os_family'] == 'Debian'

# Services
- name: Services
  ansible.builtin.import_tasks: services.yml
  tags:
    - pacemaker
    - services
  when:
    - ansible_facts['os_family'] == 'Debian'

# Corosync
- name: Corosync
  ansible.builtin.import_tasks: corosync.yml
  tags:
    - pacemaker
    - corosync
  when:
    - ansible_facts['os_family'] == 'Debian'

# Settings
- name: Settings
  ansible.builtin.import_tasks: settings.yml
  tags:
    - pacemaker
    - settings
  when:
    - ansible_facts['os_family'] == 'Debian'
