---
- name: Pacemaker | check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - pacemaker
    - network
    - packages
    - services
    - corosync
    - settings

- name: Pacemaker | network
  ansible.builtin.import_tasks: network.yml
  tags:
    - pacemaker
    - network

- name: Pacemaker | packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - pacemaker
    - packages

- name: Pacemaker | services
  ansible.builtin.import_tasks: services.yml
  tags:
    - pacemaker
    - services

- name: Pacemaker | corosync
  ansible.builtin.import_tasks: corosync.yml
  tags:
    - pacemaker
    - corosync

- name: Pacemaker | settings
  ansible.builtin.import_tasks: settings.yml
  tags:
    - pacemaker
    - settings

- name: Pacemaker | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - pacemaker
    - network
    - packages
    - services
    - corosync
    - settings
