---
- name: network | allow pacemaker tcp inbound from pacemaker servers
  community.general.ufw:
    rule: allow
    port: '{{ item[0] }}'
    proto: tcp
    direction: in
    src: '{{ item[1] }}'
  loop: "{{ query('nested', pacemaker_tcp_ports, pacemaker_hosts_list) }}"
  tags:
    - pacemaker
    - network
  when:
    - ansible_os_family == 'Debian'

- name: network | allow pacemaker udp inbound from pacemaker servers
  community.general.ufw:
    rule: allow
    port: '{{ item[0] }}'
    proto: udp
    direction: in
    src: '{{ item[1] }}'
  loop: "{{ query('nested', pacemaker_udp_ports, pacemaker_hosts_list) }}"
  tags:
    - pacemaker
    - network
  when:
    - ansible_os_family == 'Debian'
