---
- name: Services | start and enable services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - pacemaker
    - corosync
    - pcsd
  tags:
    - pacemaker
    - services
