---
- name: Services | start and enable services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - '{{ pacemaker_service_name }}'
    - '{{ corosync_service_name }}'
    - '{{ pcsd_service_name }}'
  tags:
    - pacemaker
    - services
  when:
    - ansible_facts['os_family'] == 'Debian'
