---
- name: settings | capture cluster properties
  ansible.builtin.command:
    cmd: pcs property show
  run_once: true
  register: pcs_property_show
  changed_when: false
  tags:
    - pacemaker
    - settings

- name: settings | disable stonith
  ansible.builtin.command:
    cmd: pcs property set stonith-enabled=false
  run_once: true
  tags:
    - pacemaker
    - settings
  when:
    - ansible_facts['os_family'] == 'Debian'
    - "'stonith-enabled: false' not in pcs_property_show['stdout']"
