---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd-system
spec:
  generators:
    - git:
        repoURL: https://github.com/eyulf/homelab.git
        revision: main
        files:
          - path: "kubernetes/infrastructure/**/application-config.json"
        template:
          metadata:
            name: '{{ name }}'
            annotations:
              argocd.argoproj.io/manifest-generate-paths: '/{{ folderPath }}'
          spec:
            project: default
            source:
              repoURL: https://github.com/eyulf/homelab.git
              targetRevision: main
              helm:
                valueFiles:
                  - 'values.yaml'
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{ namespace }}'
            syncPolicy:
              automated: {}
              syncOptions:
                - CreateNamespace=true
    - git:
        repoURL: https://github.com/eyulf/homelab.git
        revision: main
        files:
          - path: "kubernetes/infrastructure/**/application-objects.json"
  template:
    metadata:
      name: '{{ name }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ folderPath }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/eyulf/homelab.git
        targetRevision: main
        path: '{{ folderPath }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
