---
- name: hardware | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - hardware
    - packages
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

# Packages
- name: packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - hardware
    - packages

# Coretemp
- name: coretemp | enable coretemp
  ansible.builtin.lineinfile:
    path: /boot/loader.conf
    regexp: '^coretemp_load='
    line: coretemp_load="YES"
  tags:
    - hardware
    - coretemp
  when: ansible_facts['os_family'] == 'FreeBSD'
