---
- name: File Server | check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - file_server
    - zfs
    - syncthing
    - samba
    - backups
    - monitoring

- name: File Server | zfs
  ansible.builtin.import_tasks: zfs.yml
  tags:
    - file_server
    - zfs
  when:
    - inventory_hostname in groups['file_server']

- name: File Server | syncthing
  ansible.builtin.import_tasks: syncthing.yml
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: File Server | backups
  ansible.builtin.import_tasks: backups.yml
  tags:
    - file_server
    - backups
  when:
    - inventory_hostname in groups['file_server']

- name: File Server | monitoring
  ansible.builtin.import_tasks: monitoring.yml
  tags:
    - file_server
    - monitoring
  when:
    - inventory_hostname in groups['file_server']

- name: File Server | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - file_server
    - zfs
    - syncthing
    - samba
    - backups
    - monitoring
