---
- name: Monitoring | configure /usr/sbin/zfs-health.sh
  ansible.builtin.copy:
    src: usr/sbin/zfs-health.sh
    dest: /usr/sbin/zfs-health.sh
    owner: root
    group: root
    mode: '0750'
  tags:
    - file_server
    - monitoring
  when:
    - inventory_hostname in groups['file_server']

- name: Monitoring | configure cron - zfs-health
  ansible.builtin.cron:
    name: zfs-health
    minute: '0'
    hour: '0'
    user: root
    job: '/usr/sbin/zfs_health.sh'
    cron_file: zfs_health
  tags:
    - file_server
    - monitoring
  when:
    - inventory_hostname in groups['file_server']

- name: Monitoring | configure cron - zfs-scrub
  ansible.builtin.cron:
    name: zfs-scrub
    minute: '1'
    hour: '0'
    day: '1'
    user: root
    job: '/usr/sbin/zpool scrub storage'
    cron_file: zfs_health
  tags:
    - file_server
    - monitoring
  when:
    - inventory_hostname in groups['file_server']
