---
- name: Syncthing | install syncthing packages
  ansible.builtin.package:
    pkg: syncthing
    state: present
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: Syncthing | create syncthing user
  ansible.builtin.user:
    name: syncthing
    shell: /bin/bash
    system: true
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: Syncthing | create syncthing config dir
  ansible.builtin.file:
    path: /home/syncthing/.config/syncthing/
    state: directory
    owner: syncthing
    group: syncthing
    mode: '0700'
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: Syncthing | configure syncthing
  ansible.builtin.copy: # noqa template-instead-of-copy
    content: "{{ lookup('community.sops.sops', 'home/syncthing/.config/syncthing/config.xml', rstrip=false) }}"
    dest: /home/syncthing/.config/syncthing/config.xml
    owner: syncthing
    group: syncthing
    mode: '0600'
  notify:
    - restart syncthing
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: Syncthing | start and enable syncthing service
  ansible.builtin.service:
    name: syncthing@syncthing
    state: started
    enabled: true
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']

- name: Syncthing | allow syncthing inbound from clients
  community.general.ufw:
    rule: allow
    name: syncthing
    direction: in
    src: '{{ firewall_clients_subnet }}'
  tags:
    - file_server
    - syncthing
  when:
    - inventory_hostname in groups['file_server']
