---
- name: Docker | restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  listen: restart docker
  tags:
    - docker

- name: Docker | restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  listen: restart containerd
  tags:
    - docker
