---
- name: Docker | restart docker
  ansible.builtin.service:
    name: '{{ docker_service_name }}'
    state: restarted
  listen: restart docker
  tags:
    - docker
  when: ansible_facts['os_family'] == 'Debian'

- name: Docker | restart containerd
  ansible.builtin.service:
    name: '{{ containerd_service_name }}'
    state: restarted
  listen: restart containerd
  tags:
    - docker
  when: ansible_facts['os_family'] == 'Debian'
