---
traefik:
  logs:
    general:
      level: DEBUG
    access:
      enabled: true
  ports:
    web:
      redirectTo: websecure
    websecure:
      tls:
        enabled: true
        certResolver: "letsencrypt"
  additionalArguments:
    - "--certificatesresolvers.letsencrypt.acme.email=alex+letsencrypt@alexgardner.id.au"
    - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
    - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
  env:
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare
          key: dns-token
    - name: CLOUDFLARE_PROPAGATION_TIMEOUT
      value: "300"
