---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-stripe
  namespace: openebs-system
spec:
  pools:
    {{- range .Values.nodes }}
    - nodeSelector:
        kubernetes.io/hostname: {{ printf "%s" . | quote }}
      dataRaidGroups:
        - blockDevices:
            {{ - range $index, $device := (lookup "openebs.io/v1alpha1" "BlockDevice" "openebs-system" "").items }}
            {{ - if eq ($device).metadata.label.nodename . }}
            - blockDeviceName: {{ printf "%s" ($device).metadata.name | quote }}
            {{ - end }}
            {{ - end }}
      poolConfig:
        dataRaidGroupType: "stripe"
    {{- end }}


