---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-stripe
  namespace: openebs-system
spec:
  pools:
    {{- range $node, $bd := .Values.nodes }}
    - nodeSelector:
        kubernetes.io/hostname: {{ printf "%s" $node | quote }}
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: {{ (lookup "openebs.io/v1alpha1" "blockdevice" "" .Release.Namespace) | quote }}
      poolConfig:
        dataRaidGroupType: "stripe"
    {{- end }}
