---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-stripe
  namespace: openebs-system
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  pools:
    {{- range $node := .Values.nodes }}
    - nodeSelector:
        kubernetes.io/hostname: {{ printf "%s" $node | quote }}
      dataRaidGroups:
        - blockDevices:
          {{- range $index, $device := (lookup "openebs.io/v1alpha1" "BlockDevice" "openebs-system" "").items }}
          {{- if eq ($device).metadata.labels.nodename $node }}
          - blockDeviceName: {{ printf "%s" ($device).metadata.name | quote }}
          {{- end }}
          {{- end }}
      poolConfig:
        dataRaidGroupType: "stripe"
    {{- end }}
