---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-stripe
  namespace: openebs-system
spec:
  pools:
    {{- range $node, $blockdevice := .Values.nodes }}
    - nodeSelector:
        kubernetes.io/hostname: {{ printf "%s" $node | quote }}
      dataRaidGroups:
        - blockDevices:
          - blockDeviceName: {{ printf "%s" $blockdevice | quote }}
      poolConfig:
        dataRaidGroupType: "stripe"
    {{- end }}
