---
- name: ISCSI | install iscsi package
  ansible.builtin.package:
    pkg: open-iscsi
    state: present
  tags:
    - kubernetes
    - kubernetes-common
    - iscsi

- name: ISCSI | start and enable iscsid service
  ansible.builtin.service:
    name: iscsid
    state: started
    enabled: true
  tags:
    - kubernetes
    - kubernetes-common
    - iscsi
