---
- name: Kubernetes Worker | check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - kubernetes
    - kubernetes-worker
    - network
    - kubeadm
    - iscsi

- name: Kubernetes Worker | get service facts
  ansible.builtin.service_facts:
  tags:
    - kubernetes
    - kubernetes-worker
    - network
    - kubeadm
    - iscsi
  when:
    - inventory_hostname in groups['k8s_workers']

- name: Kubernetes Worker | network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-worker
    - network
  when:
    - inventory_hostname in groups['k8s_workers']

- name: Kubernetes Worker | kubeadm
  ansible.builtin.import_tasks: kubeadm.yml
  tags:
    - kubernetes
    - kubernetes-worker
    - kubeadm
  when:
    - inventory_hostname in groups['k8s_workers']

- name: Kubernetes Worker | iscsi
  ansible.builtin.import_tasks: iscsi.yml
  tags:
    - kubernetes
    - kubernetes-worker
    - iscsi
  when:
    - inventory_hostname in groups['k8s_workers']
