---
- name: kubernetes-worker | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - kubernetes
    - kubernetes-worker
    - network
    - kubeadm
  with_first_found:
    - '{{ ansible_facts.os_family }}.yml'
    - default.yml

# Network
- name: network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-worker
    - network
  when:
    - ansible_facts.os_family == 'Debian'
    - inventory_hostname in groups['k8s_workers']

# Kubeadm
- name: kubeadm
  ansible.builtin.import_tasks: kubeadm.yml
  tags:
    - kubernetes
    - kubernetes-worker
    - kubeadm
  when:
    - ansible_facts.os_family == 'Debian'
    - inventory_hostname in groups['k8s_workers']
