---
- name: Directories | manage kubernetes directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '755'
  loop:
    - /etc/kubernetes/
    - /etc/kubernetes/pki/
  tags:
    - kubernetes
    - kubernetes-common
    - directories
  when: ansible_facts['os_family'] == 'Debian'
