---
- name: kubernetes-common | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - kubernetes
    - kubernetes-common
    - swap
    - network
    - packages
    - directories
    - pki
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

# Swap
- name: swap
  ansible.builtin.import_tasks: swap.yml
  tags:
    - kubernetes
    - kubernetes-common
    - swap
  when: ansible_facts['os_family'] == 'Debian'

# Network
- name: network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_facts['os_family'] == 'Debian'

# Packages
- name: packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - kubernetes
    - kubernetes-common
    - packages
  when: ansible_facts['os_family'] == 'Debian'

# Directories
- name: directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - kubernetes
    - kubernetes-common
    - directories
  when: ansible_facts['os_family'] == 'Debian'

# PKI
- name: pki
  ansible.builtin.import_tasks: pki.yml
  tags:
    - kubernetes
    - kubernetes-common
    - pki
  when: ansible_facts['os_family'] == 'Debian'
