---
- name: Kubernetes Common | check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Debian. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ansible_distribution != 'Debian'
  tags:
    - kubernetes
    - kubernetes-common
    - swap
    - network
    - packages
    - directories
    - pki

- name: Kubernetes Common | swap
  ansible.builtin.import_tasks: swap.yml
  tags:
    - kubernetes
    - kubernetes-common
    - swap

- name: Kubernetes Common | network
  ansible.builtin.import_tasks: network.yml
  tags:
    - kubernetes
    - kubernetes-common
    - network

- name: Kubernetes Common | packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - kubernetes
    - kubernetes-common
    - packages

- name: Kubernetes Common | directories
  ansible.builtin.import_tasks: directories.yml
  tags:
    - kubernetes
    - kubernetes-common
    - directories

- name: Kubernetes Common | pki
  ansible.builtin.import_tasks: pki.yml
  tags:
    - kubernetes
    - kubernetes-common
    - pki
