---
- name: Network | configure /etc/modules-load.d/k8s.conf
  ansible.builtin.copy:
    src: etc/modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_facts['os_family'] == 'Debian'

- name: Network | configure /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    src: etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_facts['os_family'] == 'Debian'

- name: Network | allow kubernetes related tcp ports inbound from all kubernetes hosts
  community.general.ufw:
    rule: allow
    port: '{{ item[0] }}'
    proto: tcp
    direction: in
    src: '{{ item[1] }}'
  loop: "{{ query('nested', kubernetes_common_tcp_ports_list, kubernetes_all_hosts_list) }}"
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_facts['os_family'] == 'Debian'

- name: Network | allow kubernetes related udp ports inbound from all kubernetes hosts
  community.general.ufw:
    rule: allow
    port: '{{ item[0] }}'
    proto: udp
    direction: in
    src: '{{ item[1] }}'
  loop: "{{ query('nested', kubernetes_common_udp_ports_list, kubernetes_all_hosts_list) }}"
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_facts['os_family'] == 'Debian'
