---
- name: network | configure /etc/modules-load.d/k8s.conf
  ansible.builtin.copy:
    src: etc/modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_os_family == 'Debian'

- name: network | configure /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    src: etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - network
  when: ansible_os_family == 'Debian'
