---
- name: PKI | configure /etc/kubernetes/kubelet.conf
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'etc/kubernetes/kubelet-' + inventory_hostname + '.conf', rstrip=false) }}"
    dest: /etc/kubernetes/kubelet.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - pki
  when: ansible_facts['os_family'] == 'Debian'

- name: PKI | configure /etc/kubernetes/pki/ca.crt
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'etc/kubernetes/pki/ca.crt', rstrip=false) }}"
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0644'
  tags:
    - kubernetes
    - kubernetes-common
    - pki
  when: ansible_facts['os_family'] == 'Debian'
