---
- name: Docker | install docker key
  ansible.builtin.copy:
    src: usr/share/keyrings/docker-archive-keyring.gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    owner: root
    group: root
    mode: '0644'
  tags:
    - docker

- name: Docker | add docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ debian_version }} stable
    state: present
    filename: docker
  tags:
    - docker

- name: Docker | install docker engine packages
  ansible.builtin.package:
    pkg: '{{ item }}'
    state: present
  loop: '{{ docker_engine_packages_list }}'
  tags:
    - docker

- name: Docker | configure /etc/docker/daemon.json
  ansible.builtin.copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart docker
  tags:
    - docker

- name: Docker | configure /etc/containerd/config.toml
  ansible.builtin.copy:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart containerd
  tags:
    - docker

- name: Docker | start and enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker

- name: Docker | start and enable containerd service
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
  tags:
    - docker
