---
- name: Docker | set variables
  ansible.builtin.include_vars: '{{ item }}'
  tags:
    - docker
  with_first_found:
    - "{{ ansible_facts['os_family'] }}.yml"
    - default.yml

- name: Docker
  ansible.builtin.include_tasks: docker.yml
  tags:
    - docker
  when: ansible_facts['os_family'] == 'Debian'

# Flush Handlers
- name: Docker | flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - docker
