---
- name: k8s_controllers
  hosts: k8s_controllers
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    - common
    - docker
    - kubernetes_common
    - pacemaker
    - kubernetes_controller
    - kubernetes_bootstrap
