---
- name: k8s_all
  hosts: k8s_all
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    - common
    - docker
    - kubernetes_common

- name: k8s_controllers
  hosts: k8s_controllers
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    - pacemaker
    - kubernetes_controller

- name: k8s_workers
  hosts: k8s_workers
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    - kubernetes_worker

- name: k8s_bootstrap
  hosts: k8s_controllers
  any_errors_fatal: true
  gather_facts: true
  become: true
  roles:
    - kubernetes_bootstrap
